---
UID: 2312112014
link: ""
cssclasses: 
tags:
  - C加/异常
---

## 1 C++异常（try catch 入门）

程序的错误大致可以分为三种，分别是**语法错误**、**逻辑错误**和**运行时错误**：  
1) 语法错误在编译和链接阶段就能发现，只有 100% 符合语法规则的代码才能生成可执行程序。语法错误是最容易发现、最容易定位、最容易排除的错误，程序员最不需要担心的就是这种错误。  
  
2) 逻辑错误是说我们编写的代码思路有问题，不能够达到最终的目标，这种错误可以通过调试来解决。  
  
3) 运行时错误是指程序在运行期间发生的错误，例如除数为 0、内存分配失败、数组越界、文件不存在等。[C++](https://c.biancheng.net/cplus/) 异常（Exception）机制就是为解决运行时错误而引入的。  
  
运行时错误如果放任不管，系统就会执行默认的操作，终止程序运行，也就是我们常说的**程序崩溃（Crash）**。C++ 提供了**异常（Exception）** 机制，让我们能够捕获运行时错误，给程序一次“起死回生”的机会，或者至少告诉用户发生了什么再终止程序。

【**异常的处理流程**】

```cpp
抛出（Throw）--> 检测（Try） --> 捕获（Catch）
```

### 1.1 如何抛出异常

- 异常必须**显式地抛出**，才能被检测和捕获到；如果没有显式的抛出，即使有异常也检测不到。

在 C++ 中，我们使用 throw 关键字来显式地抛出异常，它的用法为：
```cpp
throw exceptionData;
```

`exceptionData` 是“异常数据”的意思，它可以包含任意的信息，完全有程序员决定。
- `exceptionData `的类型
	- 基本类型： int、float、bool 等，
	- 聚合类型：指针、数组、字符串、结构体、类等，


````ad-col2
title:throw 用作异常规范(了解)

throw 关键字除了可以用在函数体中抛出异常，还可以用在函数头和函数体之间，指明当前函数能够抛出的异常类型，这称为**异常规范（Exception specification）**，也称为**异常指示符**或**异常列表**。

```cpp
double func (char param) throw (int);
```
这条语句声明了一个名为 func 的函数，它的返回值类型为 double，有一个 char 类型的参数，并且只能抛出 int 类型的异常。如果抛出其他类型的异常，try 将无法捕获，只能终止程序。

如果函数会抛出多种类型的异常，那么可以用逗号隔开：
```cpp
double func (char param) throw (int, char, exception);
```

如果函数不会抛出任何异常，那么( )中什么也不写：
```cpp
double func (char param) throw ();
```

如此，func() 函数就不能抛出任何类型的异常了，即使抛出了，try 也检测不到。

- 1) 虚函数中的异常规范
	- C++ 规定，派生类虚函数的异常规范必须与基类虚函数的异常规范一样严格，或者更严格。只有这样，当通过基类指针（或者引用）调用派生类虚函数时，才能保证不违背基类成员函数的异常规范
- 2) 异常规范与函数定义和函数声明
	- C++ 规定，异常规范在函数声明和函数定义中必须同时指明，并且要严格保持一致，不能更加严格或者更加宽松。


````

>异常规范的初衷实现起来有点困难，所以大家达成的一致意见是，**最好不要使用异常规范**。异常规范是 C++98 新增的一项功能，但是后来的 C++11 已经将它抛弃了，不再建议使用。

### 1.2 如何捕获异常
#### 1.2.1 异常捕获的语法

捕获异常的语法为：
```cpp
try{  
    // 可能抛出异常的语句  
}catch(exceptionType variable){  
    // 处理异常的语句  
}
```
`try` 和 `catch` 都是 C++ 中的关键字，后跟语句块，不能省略 `{ }`。try 中包含可能会抛出异常的语句，一旦有异常抛出就会被后面的 catch 捕获。catch 关键字后面的`exceptionType variable`指明了当前 catch 可以处理的异常类型，以及具体的出错信息。

-  `try` 的意思可以看出，它只是“检测”语句块有没有异常，如果没有发生异常，它就“检测”不到。
- `catch` 是“抓住”的意思，用来捕获并处理 try 检测到的异常；
- `exceptionType variable`指明了当前 catch 可以处理的**异常类型**，以及具体的出错信息。


如果 try 语句块没有检测到异常（没有异常抛出），那么就不会执行 catch 中的语句。**检测到异常后程序的执行流会发生跳转，从异常点跳转到 catch 所在的位置**，位于异常点之后的、并且在当前 try 块内的语句就都不会再执行了；即使 catch 语句成功地处理了错误，程序的执行流也不会再回退到异常点，所以这些语句永远都没有执行的机会了。

执行完 catch 块所包含的代码后，程序会继续执行 catch 块后面的代码，就恢复了正常的执行流。

#### 1.2.2 发生异常的位置

- 异常可以发生的位置
	- 可以发生在当前的 try 块中，
	- 可以发生在 try 块所调用的某个函数中，
	- 可以发生所调用的函数又调用了另外的一个函数，这个另外的函数中发生了异常。

这些异常，都可以被 try 检测到。

#### 1.2.3 异常的类型


- `exceptionType` 是<u>异常类型</u>，它指明了当前的 catch 可以处理什么类型的异常；
	- 异常类型
		- **基本类型**： int、char、float、bool 等，
		- **聚合类型**：指针、数组、字符串、结构体、类等。
- `variable` 是一个<u>变量</u>，用来接收异常信息。当程序抛出异常时，会创建一份数据，这份数据包含了错误信息，

`exceptionType variable` 和函数的形参非常类似，当异常发生后，会将异常数据传递给 variable 这个变量，这和函数传参的过程类似。将 catch 看做一个没有返回值的函数，当异常发生后 catch 会被调用，并且会接收实参（异常数据）。

但是 catch 和真正的函数调用又有**区别**：
- 真正的函数调用，形参和实参的类型必须要匹配，或者可以自动转换，否则在编译阶段就报错了。
- 而对于 catch，异常是在运行阶段产生的，它可以是任何类型，没法提前预测，所以不能在编译阶段判断类型是否正确，只能等到程序运行后，真的抛出异常了，再将异常类型和 catch 能处理的类型进行匹配，匹配成功的话就“调用”当前的 catch，否则就忽略当前的 catch。

总起来说，catch 和真正的函数调用相比，多了一个「**在运行阶段将实参和形参匹配**」的过程。

````ad-def
title:参考理解
`exceptionType`是异常类型，它指明了当前的 catch 可以处理什么类型的异常；`variable`是一个变量，用来接收异常信息。当程序抛出异常时，会创建一份数据，这份数据包含了错误信息，程序员可以根据这些信息来判断到底出了什么问题

异常既然是一份数据，那么就应该有数据类型。[C++](https://c.biancheng.net/cplus/) 规定，异常类型可以是 int、char、float、bool 等基本类型，也可以是[指针](https://c.biancheng.net/c/80/)、数组、字符串、结构体、类等聚合类型。C++ 语言本身以及标准库中的函数抛出的异常，都是 exception 类或其子类的异常。也就是说，抛出异常时，会创建一个 exception 类或其子类的对象。


`exceptionType variable` 和函数的形参非常类似，当异常发生后，会将异常数据传递给 variable 这个变量，这和函数传参的过程类似。当然，只有跟 exceptionType 类型匹配的异常数据才会被传递给 variable，否则 catch 不会接收这份异常数据，也不会执行 catch 块中的语句。换句话说，catch 不会处理当前的异常。  
  
我们可以将 catch 看做一个没有返回值的函数，当异常发生后 catch 会被调用，并且会接收实参（异常数据）。  
  
但是 catch 和真正的函数调用又有区别：

- 真正的函数调用，形参和实参的类型必须要匹配，或者可以自动转换，否则在编译阶段就报错了。
- 而对于 catch，异常是在运行阶段产生的，它可以是任何类型，没法提前预测，所以不能在编译阶段判断类型是否正确，只能等到程序运行后，真的抛出异常了，再将异常类型和 catch 能处理的类型进行匹配，匹配成功的话就“调用”当前的 catch，否则就忽略当前的 catch。

  
总起来说，catch 和真正的函数调用相比，多了一个「在运行阶段将实参和形参匹配」的过程。  
  
另外需要注意的是，如果不希望 catch 处理异常数据，也可以将 variable 省略掉，也即写作：  

```cpp
try{  
    // 可能抛出异常的语句  
}catch(exceptionType){  
    // 处理异常的语句  
}
```
这样只会将异常类型和 catch 所能处理的类型进行匹配，不会传递异常数据了。

````


#### 1.2.4 多级 catch

一个 try 后面可以跟多个 catch：
```cpp
try{
    //可能抛出异常的语句
}catch (exception_type_1 e){
    //处理异常的语句
}catch (exception_type_2 e){
    //处理异常的语句
}
//其他的catch
catch (exception_type_n e){
    //处理异常的语句
}
```

当异常发生时，程序会按照从上到下的顺序，将异常类型和 catch 所能接收的类型逐个匹配。一旦找到类型匹配的 catch 就停止检索，并将异常交给当前的 catch 处理（其他的 catch 不会被执行）。如果最终也没有找到匹配的 catch，就只能交给系统处理，终止程序的运行。


#### 1.2.5 catch 在匹配过程中的类型转换

- catch 在匹配异常类型的过程中，也会进行类型转换：
	- 「向上转型」
	- 「const 转换」
	- 「数组或函数指针转换」


````ad-def
title:参考解释
C/C++ 中存在多种多样的类型转换，以普通函数（非模板函数）为例，发生函数调用时，如果实参和形参的类型不是严格匹配，那么会将实参的类型进行适当的转换，以适应形参的类型，这些转换包括：

- 算数转换：例如 int 转换为 float，char 转换为 int，double 转换为 int 等。
- 向上转型：也就是派生类向基类的转换。
- const 转换：也即将非 const 类型转换为 const 类型，例如将 `char * `转换为 `const char *`。
- 数组或函数指针转换：如果函数形参不是引用类型，那么数组名会转换为数组指针，函数名也会转换为函数指针。
- 用户自定的类型转换。

  
catch 在匹配异常类型的过程中，也会进行类型转换，但是这种转换受到了更多的限制，仅能进行「向上转型」、「const 转换」和「数组或函数指针转换」，其他的都不能应用于 catch。

1. 向上转型

```cpp
[[include]] <iostream>
[[include]] <string>
using namespace std;
class Base{ };
class Derived: public Base{ };
int main(){
    try{
        throw Derived();  //抛出自己的异常类型，实际上是创建一个Derived类型的匿名对象
        cout<<"This statement will not be executed."<<endl;
    }catch(int){
        cout<<"Exception type: int"<<endl;
    }catch(char *){
        cout<<"Exception type: cahr *"<<endl;
    }catch(Base){  //匹配成功（向上转型）
        cout<<"Exception type: Base"<<endl;
    }catch(Derived){
        cout<<"Exception type: Derived"<<endl;
    }
    return 0;
}
```
运行结果：  
Exception type: Base

本例中，我们定义了一个基类 Base，又从 Base 派生类出了 Derived。抛出异常时，我们创建了一个 Derived 类的匿名对象，也就是说，异常的类型是 Derived。  
  
我们期望的是，异常被`catch(Derived)`捕获，但是从输出结果可以看出，异常提前被`catch(Base)`捕获了，这说明 catch 在匹配异常类型时发生了向上转型（Upcasting）。

const转换，数据和指针转换

```cpp
[[include]] <iostream>
using namespace std;
int main(){
    int nums[] = {1, 2, 3};
    try{
        throw nums;
        cout<<"This statement will not be executed."<<endl;
    }catch(const int *){
        cout<<"Exception type: const int *"<<endl;
    }
    return 0;
}
```
运行结果：  
Exception type: const int *

nums 本来的类型是`int [3]`，但是 catch 中没有严格匹配的类型，所以先转换为`int *`，再转换为`const int *`。

````


## 2 C++ exception 类：C++标准异常的基类

C++语言本身或者标准库抛出的异常都是 exception 的子类，称为标准异常（Standard Exception）。你可以通过下面的语句来捕获所有的标准异常：
```cpp
try{
    //可能抛出异常的语句
}catch(exception &e){
    //处理异常的语句
}
```

之所以使用引用，是为了提高效率。如果不使用引用，就要经历一次对象拷贝（要调用拷贝构造函数）的过程。

exception 类位于 `<exception>` 头文件中，它被声明为：
```cpp
class exception{
public:
    exception () throw();  //构造函数
    exception (const exception&) throw();  //拷贝构造函数
    exception& operator= (const exception&) throw();  //运算符重载
    virtual ~exception() throw();  //虚析构函数
    virtual const char* what() const throw();  //虚函数
}
```

这里需要说明的是 what() 函数。what() 函数返回一个能识别异常的字符串，正如它的名字“what”一样，可以粗略地告诉你这是什么异常。不过C++标准并没有规定这个字符串的格式，各个编译器的实现也不同，所以 what() 的返回值仅供参考。

下图展示了 exception 类的继承层次：
![[07_C++异常.md_Attachments/07_C++异常.png]]
图：exception 类的继承层次以及它们所对应的头文件


先来看一下 exception 类的直接派生类：

|异常名称|说  明|
|---|---|
|logic_error|逻辑错误。|
|runtime_error|运行时错误。|
|bad_alloc|使用 new 或 new[ ] 分配内存失败时抛出的异常。|
|bad_typeid|使用 typeid 操作一个 NULL指针，而且该指针是带有虚函数的类，这时抛出 bad_typeid 异常。|
|bad_cast|使用 dynamic_cast 转换失败时抛出的异常。|
|ios_base::failure|io 过程中出现的异常。|
|bad_exception|这是个特殊的异常，如果函数的异常列表里声明了 bad_exception 异常，当函数内部抛出了异常列表中没有的异常时，如果调用的 unexpected() 函数中抛出了异常，不论什么类型，都会被替换为 bad_exception 类型。|

 logic_error 的派生类：   

|异常名称|说  明|
|---|---|
|length_error|试图生成一个超出该类型最大长度的对象时抛出该异常，例如 vector 的 resize 操作。|
|domain_error|参数的值域错误，主要用在数学函数中，例如使用一个负值调用只能操作非负数的函数。|
|out_of_range|超出有效范围。|
|invalid_argument|参数不合适。在标准库中，当利用string对象构造 bitset 时，而 string 中的字符不是 0 或1 的时候，抛出该异常。|


runtime_error 的派生类：   

|异常名称|说  明|
|---|---|
|range_error|计算结果超出了有意义的值域范围。|
|overflow_error|算术计算上溢。|
|underflow_error|算术计算下溢。|



















